exclude: ['README.md', 'assets/latex/', 'archive']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2023su-cmpt-983-x1/"
semcode: 1234
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Aug 4, 2023"
midterm: "NA"
instructor: anoop
tas:
  - name: "Hassan Shavarani"
    email: sshavara
    officehour: "TBD"
  - name: "Sha Hu"
    email: hushah
    officehour: "TBD"
hwdates:
  - hw: "0"
    startdate: "May 15, 2023"
    deadline: "May 29, 2023"
  - hw: "1"
    startdate: "May 23, 2023"
    deadline: "June 5, 2023"
  - hw: "2"
    startdate: "June 12, 2023"
    deadline: "June 26, 2023"
  - hw: "3"
    startdate: "June 26, 2023"
    deadline: "July 10, 2023"
  - hw: "4"
    startdate: "July 10, 2023"
    deadline: "July 24, 2023"
  - hw: "project"
    startdate: "June 26, 2023"
    deadline: "Aug 8, 2023"
    time: "Poster session:"
    location: "ASB Atrium (tentative)"
    proposal: "Aug 10, 2023"
