exclude: ['README.md', 'assets/latex/', 'archive']
timezone: US/Pacific
markdown: kramdown
coursys: "https://coursys.sfu.ca/2023su-cmpt-983-x1/"
semcode: 1234
calendar: "https://calendar.google.com/calendar/ical/qgs97od9ef8t1582k2rqomv5ho%40group.calendar.google.com/public/basic.ics"
lastday: "Aug 4, 2023"
midterm: "TBD"
instructor: anoop
tas:
  - name: "Hassan Shavarani"
    email: sshavara
    officehour: "TBD"
  - name: "Sha Hu"
    email: hushah
    officehour: "TBD"
hwdates:
  - hw: "0"
    startdate: "TBD"
    deadline: "TBD"
  - hw: "1"
    startdate: "TBD"
    deadline: "TBD"
  - hw: "2"
    startdate: "TBD"
    deadline: "TBD"
  - hw: "3"
    startdate: "TBD"
    deadline: "TBD"
  - hw: "4"
    startdate: "TBD"
    deadline: "TBD"
  - hw: "project"
    startdate: "TBD"
    deadline: "TBD"
    time: "Poster session: TBD"
    location: "TBD"
    proposal: "TBD"
